sudo: false
language: scala
# Activator & Travis image SBT conflicts
# https://github.com/travis-ci/travis-ci/issues/3140
before_install: unset SBT_OPTS JVM_OPTS
# according to http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS
# every travis CI has a version of ruby installed
# that's why we can do this
before_script:
  - wget https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6-minimal.zip
  - unzip -q typesafe-activator-1.3.6-minimal.zip
  - if $RUN_RUBY; then gem install bundler; fi

cache:
  directories:
    # caching scala stuff based on
    # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    # cache each of the bundle from the ruby tests
    - support/ruby/collins-client/vendor/bundle
    - support/ruby/collins-state/vendor/bundle
    - support/ruby/consolr/vendor/bundle

jdk:
  - oraclejdk7
scala:
  - 2.11.1
# this will make sure we run each of the scala and ruby tests once
env:
  - RUN_SCALA=true RUN_RUBY=false
matrix:
  include:
    - jdk: oraclejdk7
      env: RUN_RUBY=true RUN_SCALA=false GEM_NAME=collins-client
    - jdk: oraclejdk7
      env: RUN_RUBY=true RUN_SCALA=false GEM_NAME=collins-state
    - jdk: oraclejdk7
      env: RUN_RUBY=true RUN_SCALA=false GEM_NAME=consolr
script:
  - if $RUN_SCALA; then activator-1.3.6-minimal/activator test; fi
  - if $RUN_RUBY; then cd support/ruby/$GEM_NAME; bundle install --path ./vendor/bundle; bundle exec rake; fi
  # cleanup travis trick from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  irc: "chat.freenode.net#collins"
