language: scala
# according to http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS
# every travis CI has a version of ruby installed
# that's why we can do this
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.4/typesafe-activator-1.3.4-minimal.zip
  - unzip -q typesafe-activator-1.3.4-minimal.zip
  - if $RUN_RUBY; then gem install bundler; fi
jdk:
  - oraclejdk7
scala:
  - 2.11.1
# this will make sure we run each of the scala and ruby tests once
env:
  - RUN_SCALA=true RUN_RUBY=false
matrix:
  include:
    - jdk: oraclejdk7
      env: RUN_RUBY=true RUN_SCALA=false GEM_NAME=collins-client
    - jdk: oraclejdk7
      env: RUN_RUBY=true RUN_SCALA=false GEM_NAME=collins-state
script:
  - if $RUN_SCALA; then activator-1.3.4-minimal/activator test; fi
  - if $RUN_RUBY; then cd support/ruby/$GEM_NAME; bundle install --path ./vendor/bundle; bundle exec rake; fi
notifications:
  irc: "chat.freenode.net#collins"
